### PR TITLE
HOPSWORKS-1196 append

### PR DESCRIPTION
**Pull request by Limmen**

### CODE REVIEW

**Comment by Limmen** [comment]
Prs:

https://github.com/logicalclocks/hops-util/pull/48
https://github.com/logicalclocks/hopsworks/pull/302

**Comment by Limmen** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Pull request closed without merging**
