### PR TITLE
[HOPSWORKS-1418] Pytorch 1.3 and numpy version upgrade

### PR DESCRIPTION
**Pull request by jimdowling**
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1418

### CODE REVIEW

**Comment by robzor92** [comment]
Upgrading pytorch also means testing it on a CPU machine (vm) and a GPU machine. Also fixing all pytorch notebooks which may break as a result of the upgrade which you find in both https://github.com/logicalclocks/hops-examples/tree/master/notebooks/featurestore and https://github.com/logicalclocks/hops-examples/tree/master/notebooks/ml

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Pull request closed without merging**
