### PR TITLE
[HOPSWORKS-1073] Use nvidia-ml-py to get GPU information

### PR DESCRIPTION
**Pull request by robzor92**

### CODE REVIEW

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Pull request closed without merging**
