### PR TITLE
[HOPSWORKS-897] Hopsworks-ca should set expiration date not validity …

### PR DESCRIPTION
**Pull request by SirOibaf**
…in days

### CODE REVIEW

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
@SirOibaf can you exclude the test_manifest and merge the pr?

**Pull request closed without merging**
