### PR TITLE
[test_HOPSWORKS-1174] test

### PR DESCRIPTION
**Pull request by kouzant**

### CODE REVIEW

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
@kouzant Is this WIP?

**Comment by kouzant** [comment]
Yes, I had to fix https://hopshadoop.atlassian.net/browse/HOPS-1439 first

**Pull request closed without merging**
