### PR TITLE
[test_HOPSWORKS-1236] Test HOPSWORKS-1236

### PR DESCRIPTION
**Pull request by kouzant**

### CODE REVIEW

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Pull request closed without merging**
