### PR TITLE
HOPSWORKS-243 ELK 6.2.3 upgrade

### PR DESCRIPTION
**Pull request by robzor92**

### CODE REVIEW

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Pull request closed without merging**
