### PR TITLE
HOPSWORKS-1229 - conda update to 4.7

### PR DESCRIPTION
**Pull request by jimdowling**
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1229

This PR worked with the conda default channel, but not with our copy of the conda channel:

  conda:
    use_defaults: false
    channels:
      default_mirrors: http://snurran.sics.se/hops/conda/pkgs/main/linux-64,http://snurran.sics.se/hops/conda/pkgs/main/noarch

Maybe there is a more up-to-date copy of the conda repo somewhere, like bbc2?

### CODE REVIEW

**Comment by jimdowling** [comment]
jenkins, test this please.

**Comment by jimdowling** [comment]
This PR worked with the conda default channel, but not with our copy of the conda channel:

  conda:
    use_defaults: false
    channels:
      default_mirrors: http://snurran.sics.se/hops/conda/pkgs/main/linux-64,http://snurran.sics.se/hops/conda/pkgs/main/noarch

Maybe there is a more up-to-date copy of the conda repo somewhere, like bbc2?

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
@jimdowling It fails with 
```
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <http://bbc2.sics.se:8000/pkgs/main/linux-64/future-0.17.1-py37_0.conda>
Elapsed: 00:00.007258
```
You can talk to @SirOibaf for updating the mirror

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Pull request merged**
