### PR TITLE
[HOPSWORKS-1095] Add back Localhost support

### PR DESCRIPTION
**Pull request by jimdowling**
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1095

### CODE REVIEW

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Pull request closed without merging**
