### PR TITLE
[HOPSWORKS-1558] test cluster share

### PR DESCRIPTION
**Pull request by o-alex**

### CODE REVIEW

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Pull request closed without merging**
