### PR TITLE
HOPSWORKS-967

### PR DESCRIPTION
**Pull request by o-alex**

### CODE REVIEW

**Comment by o-alex** [comment]
Jenkins test this please.

**Comment by o-alex** [comment]
Jenkins test this please.

**Comment by tkakantousis** [comment]
@o-alex please change title to `HOPSWORKS-967`, other JIRA won't pick up the PR.

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please.

**Comment by o-alex** [comment]
> @o-alex please change title to `HOPSWORKS-967`, other JIRA won't pick up the PR.
> Also can you submit the hops-hadoop-chef PR?

**Comment by o-alex** [comment]
Jenkins test this please.

**Comment by o-alex** [comment]
> @o-alex please change title to `HOPSWORKS-967`, other JIRA won't pick up the PR.
> Also can you submit the hops-hadoop-chef PR?
There is a open PR on hops-hadoop-chef for this

**Comment by o-alex** [comment]
Jenkins test this please.

**Comment by o-alex** [comment]
Jenkins test this please.

**Comment by o-alex** [comment]
Jenkins test this please.

**Pull request closed without merging**
