### PR TITLE
HOPSWORKS-1384

### PR DESCRIPTION
**Pull request by kai-chi**

### CODE REVIEW

**Comment by kai-chi** [comment]
Jenkins test this please

**Comment by kai-chi** [comment]
Jenkins test this please

**Comment by kai-chi** [comment]
Jenkins test this please

**Comment by kai-chi** [comment]
Jenkins test this please

**Comment by kai-chi** [comment]
Jenkins test this please

**Comment by kai-chi** [comment]
Jenkins test this please

**Comment by kai-chi** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by kai-chi** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
%(/Ro@D6$?yE!R+Rp7w%

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by kai-chi** [comment]
Jenkins test this please

**Pull request closed without merging**
