### PR TITLE
HOPSWORKS-1196

### PR DESCRIPTION
**Pull request by Limmen**

### CODE REVIEW

**Comment by Limmen** [comment]
PRs:

https://github.com/logicalclocks/hops-util/pull/43
https://github.com/logicalclocks/hopsworks-chef/pull/316
https://github.com/logicalclocks/spark-chef/pull/67
https://github.com/logicalclocks/hops-util-py/pull/93

**Comment by Limmen** [comment]
Jenkins test this please

**Comment by Limmen** [comment]
Jenkins test this please

**Comment by Limmen** [comment]
Test results: https://bbc1.sics.se/jenkins/job/HopsWorks-testing/1692

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Pull request closed without merging**
