### PR TITLE
[HOPSWORKS-1069] Add new chef attribute for hopsworks/https/port. Remove hopsworks/secure_port

### PR DESCRIPTION
**Pull request by jimdowling**

### CODE REVIEW

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Pull request closed without merging**
