### PR TITLE
 [HOPSWORKS-627][HOPSWORKS-603] Chef fixes jd

### PR DESCRIPTION
**Pull request by jimdowling**
Couple of upgrades: ndb to 7.6.7 and tensorflow to 1.10.

### CODE REVIEW

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by SirOibaf** [comment]
```
logicalclocks/conda-chef/chef_fixes_jd
logicalclocks/hops-hadoop-chef/chef_fixes_jd
logicalclocks/flink-chef/chef_fixes_jd
logicalclocks/livy-chef/chef_fixes_jd
logicalclocks/tensorflow-chef/chef_fixes_jd
logicalclocks/kzookeeper/chef_fixes_jd
logicalclocks/kafka-cookbook/chef_fixes_jd
logicalclocks/hopslog-chef/chef_fixes_jd
logicalclocks/hopsmonitor-chef/chef_fixes_jd
logicalclocks/chef-glassfish/chef_fixes_jd
logicalclocks/hive-chef/chef_fixes_jd
```
These branches have been merged

**Comment by SirOibaf** [comment]
`logicalclocks/kagent-chef/chef_fixes_jd` merged

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Comment by jimdowling** [comment]
Jenkins, test this please.

**Pull request closed without merging**
