### PR TITLE
[HOPSWORKS-1546] test

### PR DESCRIPTION
**Pull request by o-alex**

### CODE REVIEW

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Pull request closed without merging**
