### PR TITLE
[HOPSWORKS-1607] test move entities to persistence

### PR DESCRIPTION
**Pull request by ErmiasG**

### CODE REVIEW

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Pull request merged**
