### PR TITLE
[HOPSWORKS-1609][ePipe] Fix version conflicts in Elasticsearch

### PR DESCRIPTION
**Pull request by maismail**
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1609

### CODE REVIEW

**Comment by maismail** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by maismail** [comment]
Jenkins test this please

**Pull request closed without merging**
