### PR TITLE
HOPSWORKS-1627

### PR DESCRIPTION
**Pull request by SirOibaf**

### CODE REVIEW

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by kouzant** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Pull request closed without merging**
