### PR TITLE
[HOPSWORKS-1114] test password reset

### PR DESCRIPTION
**Pull request by ErmiasG**

### CODE REVIEW

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Pull request closed without merging**
