### PR TITLE
[HOPSWORKS-875] Add PyTorch, Torchvision and Matplotlib to python base environment

### PR DESCRIPTION
**Pull request by robzor92**
…e environment

### CODE REVIEW

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Pull request closed without merging**
