### PR TITLE
HOPSWORKS-510

### PR DESCRIPTION
**Pull request by tkakantousis**

### CODE REVIEW

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
@SirOibaf 
I think something might be wrong with my PR and it fails when checking licenses
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/HopsWorks-testing@5/scripts/license_checker.py", line 169, in <module>
    main(args.dir, args.whitelist_dir, args.branch, args.fork_commit)
  File "/home/jenkins/workspace/HopsWorks-testing@5/scripts/license_checker.py", line 143, in main
    if not check_file(repo, entry.path, entry.abspath, branch, shas, fork_commit, fork_commit_idx, lc_files):
  File "/home/jenkins/workspace/HopsWorks-testing@5/scripts/license_checker.py", line 100, in check_file
    first_commit_idx = shas.index(revisions[-1])
ValueError: '88359663fc655c52ac808b21de46ddbb18341e9e' is not in list
```
Like I'm missing a commit or something. Any ideas?

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Pull request closed without merging**
