### PR TITLE
[HOPSWORKS-851] nbconvert .ipynb to .py file broken

### PR DESCRIPTION
**Pull request by robzor92**

### CODE REVIEW

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
@tkakantousis please review, merge if ok.

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Pull request closed without merging**
