### PR TITLE
[HOPSWORKS-1070] Refactor HdfsLeDescriptorsFacade to return a random NN

### PR DESCRIPTION
**Pull request by robzor92**

### CODE REVIEW

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Pull request closed without merging**
