### PR TITLE
[HOPSWORKS-1578] test epipe provenance fix

### PR DESCRIPTION
**Pull request by o-alex**

### CODE REVIEW

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Pull request closed without merging**
