### PR TITLE
[HOPSWORKS-1077] Review overridable Spark configuration properties for SparkJobConfiguration

### PR DESCRIPTION
**Pull request by robzor92**

### CODE REVIEW

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by Limmen** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Comment by robzor92** [comment]
Jenkins test this please

**Pull request closed without merging**
