### PR TITLE
JWT for new REST API endpoints

### PR DESCRIPTION
**Pull request by ErmiasG**

### CODE REVIEW

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Pull request closed without merging**
