### PR TITLE
HOPSWORKS-1025

### PR DESCRIPTION
**Pull request by Limmen**

### CODE REVIEW

**Comment by Limmen** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this pease

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by Limmen** [comment]
Jenkins test this please

**Comment by Limmen** [comment]
Jenkins test this please

**Comment by Limmen** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by Limmen** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by Limmen** [comment]
Jenkins test this please

**Pull request closed without merging**
