### PR TITLE
[HOPSWORKS-1619] test zip/unzip dirs with url encoded chars

### PR DESCRIPTION
**Pull request by ErmiasG**

### CODE REVIEW

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by o-alex** [comment]
Jenkins test this please

**Pull request closed without merging**
