### PR TITLE
[HOPSWORKS-762] test python api

### PR DESCRIPTION
**Pull request by ErmiasG**

### CODE REVIEW

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by ErmiasG** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Pull request closed without merging**
